<div class="span4 column-left">
    <nav class="secondaryPageNav">
        <div class="tabbable tabs-left">
            <ul>
            <li class="pageNavTitle">
                <a href="index.php" class="pageNavTitle_elt"> Experiments </a></li>
            </ul>
            <ul class="nav nav-tabs" id="myTab">
                <li><a href="index.php">Home</a></li>
                <li><a href="visual_search.php">Visual Search</a></li>
                <li><a href="sternberg.php">Sternberg</a></li>
                <li><a href="reverse_stroop.php">Reverse Stroop</a></li>
                <li><a href="index.php#density" class="tab-link">Pattern Density</a></li>
                <li><a href="index.php#RSVP" class="tab-link">Rapid Sentence Reading</a></li>
            </ul>
        </div>
    </nav>

    <div class="module_type2">
        <div class="module_title">
            <h3> Contact Info </h3>
        </div>
        
        <div class="module_content about">
            <p> Frank Durgin <br> Professor of Psychology <br>Director, Perception Laboratory </p>
            <p> Office: Papazian 223&nbsp;<br>Phone: (610) 328-8678 <br>Fax: (610) 328-7814 <br>Email: <a href="mailto:fdurgin1@swarthmore.edu">fdurgin1@swarthmore.edu</a> </p>
            <p>Swarthmore College <br>500 College Avenue <br>Swarthmore, PA, 19081 USA </p>
        </div>
    </div>
</div>